/* Generated by build_release.py. Never edit sw.js directly. */
'use strict';
const RELEASE={"app_version":"3.8.0","shell_id":"3.8.0-68dc4693f77cdb20","files":{"index.html":"e3f56f5cfa42e73c3ce72f62dade4800d6ae25a878f86c5bf77d6da63dbdd6dd","pwa.js":"093096beb0408cc7f65f007c19d8d404a46e7e26dd294fe72f2f47c19cbb888d","core.js":"f85676139cfea94d996d1bec159daaf2d3403ef42b70a1329a3745a66650a287","app.js":"83cf0e3858389284403d5519b6d43fd2ccae7458500e16d2da0c895327802a50","manifest.webmanifest":"c9d03affcc5a4c8f81ce381129827f5f271cc73acde8da25071042a409bb334b","icon-192.png":"5bb1d5d0a6dee0f338cc80569f92ba3e81eaea5f4ae22bfbabcdf4155d20e583","icon-512.png":"a3eecdee3121cc04c6cd7a7cdc54d52c4de69876cafc167496b3b06d30fdf42e","icon-maskable-512.png":"a3eecdee3121cc04c6cd7a7cdc54d52c4de69876cafc167496b3b06d30fdf42e","apple-touch-icon.png":"a00b56491e3663b8de34377dff3fd0d6d63889767761d6008fd935d34ba5d26f"}};
const BASE=new URL('./',self.location.href);
const PREFIX='lap-section-shell-'+encodeURIComponent(BASE.pathname)+'-';
const CACHE=PREFIX+RELEASE.shell_id;
async function hash(bytes){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(x=>x.toString(16).padStart(2,'0')).join('')}
self.addEventListener('install',event=>{
 event.waitUntil((async()=>{
  // Download and verify every asset before writing the new shell generation.
  const assets=await Promise.all(Object.entries(RELEASE.files).map(async([path,expected])=>{
   const url=new URL(path,BASE),r=await fetch(url,{cache:'no-store'});
   if(!r.ok)throw new Error(path+': HTTP '+r.status);
   if(await hash(await r.clone().arrayBuffer())!==expected)throw new Error(path+': shell mismatch');
   return [url.href,r];
  }));
  try{const cache=await caches.open(CACHE);for(const [url,r]of assets)await cache.put(url,r)}
  catch(e){await caches.delete(CACHE);throw e}
  await self.skipWaiting();
 })());
});
self.addEventListener('activate',event=>{
 event.waitUntil((async()=>{
  const keys=await caches.keys();
  await Promise.all(keys.filter(k=>k.startsWith(PREFIX)&&k!==CACHE).map(k=>caches.delete(k)));
  await self.clients.claim();
 })());
});
self.addEventListener('fetch',event=>{
 const r=event.request;if(r.method!=='GET')return;const u=new URL(r.url);
 if(u.origin!==BASE.origin||!u.pathname.startsWith(BASE.pathname))return;
 const path=u.pathname.slice(BASE.pathname.length);
 // JSON has no per-file fallback/cache. app.js commits verified complete snapshots.
 if(path.endsWith('.json')){event.respondWith(fetch(r));return}
 const asset=path===''?'index.html':path;
 if(!Object.hasOwn(RELEASE.files,asset))return;
 event.respondWith((async()=>{
  const cache=await caches.open(CACHE),key=new URL(asset,BASE).href,hit=await cache.match(key);
  if(hit)return hit;
  const response=await fetch(new URL(asset,BASE),{cache:'no-store'});
  if(!response.ok)return response;
  if(await hash(await response.clone().arrayBuffer())!==RELEASE.files[asset])return new Response('アプリの世代が一致しません。画面を閉じて開き直してください。',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}});
  await cache.put(key,response.clone());return response;
 })());
});
