#!/usr/bin/env python3
"""Generate the v380-test service worker and verified shell manifest."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
APP_VERSION = "3.8.0"
ASSETS = (
    "index.html",
    "pwa.js",
    "core.js",
    "app.js",
    "manifest.webmanifest",
    "icon-192.png",
    "icon-512.png",
    "icon-maskable-512.png",
    "apple-touch-icon.png",
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


files = {name: sha256(ROOT / name) for name in ASSETS}
shell_inputs = {"files": files, "generator": sha256(Path(__file__))}
shell_digest = hashlib.sha256(json.dumps(shell_inputs, sort_keys=True).encode()).hexdigest()[:16]
release = {"app_version": APP_VERSION, "shell_id": f"{APP_VERSION}-{shell_digest}", "files": files}
release_json = json.dumps(release, ensure_ascii=False, separators=(",", ":"))

source = f'''/* Generated by build_release.py. Never edit sw.js directly. */
'use strict';
const RELEASE={release_json};
const BASE=new URL('./',self.location.href);
const PREFIX='lap-section-shell-'+encodeURIComponent(BASE.pathname)+'-';
const CACHE=PREFIX+RELEASE.shell_id;
async function hash(bytes){{return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(x=>x.toString(16).padStart(2,'0')).join('')}}
self.addEventListener('install',event=>{{
 event.waitUntil((async()=>{{
  // Download and verify every asset before writing the new shell generation.
  const assets=await Promise.all(Object.entries(RELEASE.files).map(async([path,expected])=>{{
   const url=new URL(path,BASE),r=await fetch(url,{{cache:'no-store'}});
   if(!r.ok)throw new Error(path+': HTTP '+r.status);
   if(await hash(await r.clone().arrayBuffer())!==expected)throw new Error(path+': shell mismatch');
   return [url.href,r];
  }}));
  try{{const cache=await caches.open(CACHE);for(const [url,r]of assets)await cache.put(url,r)}}
  catch(e){{await caches.delete(CACHE);throw e}}
  await self.skipWaiting();
 }})());
}});
self.addEventListener('activate',event=>{{
 event.waitUntil((async()=>{{
  const keys=await caches.keys();
  await Promise.all(keys.filter(k=>k.startsWith(PREFIX)&&k!==CACHE).map(k=>caches.delete(k)));
  await self.clients.claim();
 }})());
}});
self.addEventListener('message',event=>{{
 if(event.data?.type==='GET_SHELL_ID'&&event.ports[0])event.ports[0].postMessage(RELEASE.shell_id);
}});
self.addEventListener('fetch',event=>{{
 const r=event.request;if(r.method!=='GET')return;const u=new URL(r.url);
 if(u.origin!==BASE.origin||!u.pathname.startsWith(BASE.pathname))return;
 const path=u.pathname.slice(BASE.pathname.length);
 // JSON has no per-file fallback/cache. app.js commits verified complete snapshots.
 if(path.endsWith('.json')){{event.respondWith(fetch(r));return}}
 const asset=path===''?'index.html':path;
 if(!Object.hasOwn(RELEASE.files,asset))return;
 event.respondWith((async()=>{{
  const cache=await caches.open(CACHE),key=new URL(asset,BASE).href,hit=await cache.match(key);
  if(hit)return hit;
  const response=await fetch(new URL(asset,BASE),{{cache:'no-store'}});
  if(!response.ok)return response;
  if(await hash(await response.clone().arrayBuffer())!==RELEASE.files[asset])return new Response('アプリの世代が一致しません。画面を閉じて開き直してください。',{{status:503,headers:{{'Content-Type':'text/plain; charset=utf-8'}}}});
  await cache.put(key,response.clone());return response;
 }})());
}});
'''

(ROOT / "sw.js").write_text(source, encoding="utf-8")
print(release["shell_id"])
