/* Generated by tools/build_release.py. Never edit sw.js directly. */
'use strict';
const RELEASE={"app_version":"3.3.0","shell_id":"3.3.0-1682b716cee35430","files":{"index.html":"d2083ab30453ac676348f031d10bbac4b7fb06e5544db69acd8b30c758f129c5","core.js":"58266d3bd4f09b804aa06d48fbe0ec512b4cfb3fc5711891a53fc9b4abb72a41","app.js":"58034b8324f72794a69f0170974bdebe266ec52369171b7466a5129d43b78439","manifest.webmanifest":"a0442b8b5ac7133a18c7e764584cd797fe00113974b97b06682cc275921ec688","icon-192.png":"5bb1d5d0a6dee0f338cc80569f92ba3e81eaea5f4ae22bfbabcdf4155d20e583","icon-512.png":"a3eecdee3121cc04c6cd7a7cdc54d52c4de69876cafc167496b3b06d30fdf42e","icon-maskable-512.png":"a3eecdee3121cc04c6cd7a7cdc54d52c4de69876cafc167496b3b06d30fdf42e","apple-touch-icon.png":"a00b56491e3663b8de34377dff3fd0d6d63889767761d6008fd935d34ba5d26f"}};
const BASE=new URL('./',self.location.href);
const PREFIX='lap-section-shell-'+encodeURIComponent(BASE.pathname)+'-';
const CACHE=PREFIX+RELEASE.shell_id;
async function hash(bytes){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(x=>x.toString(16).padStart(2,'0')).join('')}
self.addEventListener('install',event=>{
 event.waitUntil((async()=>{
  // Download and verify every asset before writing the new shell generation.
  const assets=await Promise.all(Object.entries(RELEASE.files).map(async([path,expected])=>{
   const url=new URL(path,BASE),r=await fetch(url,{cache:'no-store'});
   if(!r.ok)throw new Error(path+': HTTP '+r.status);
   if(await hash(await r.clone().arrayBuffer())!==expected)throw new Error(path+': shell mismatch');
   return [url.href,r];
  }));
  try{const cache=await caches.open(CACHE);for(const [url,r]of assets)await cache.put(url,r)}
  catch(e){await caches.delete(CACHE);throw e}
  // No skipWaiting: a shell must not replace the shell of already-open clients.
 })());
});
self.addEventListener('activate',event=>{
 event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith(PREFIX)&&k!==CACHE).map(k=>caches.delete(k)))));
 // No clients.claim: first-load documents keep their own generation until reload.
});
self.addEventListener('fetch',event=>{
 const r=event.request;if(r.method!=='GET')return;const u=new URL(r.url);
 if(u.origin!==BASE.origin||!u.pathname.startsWith(BASE.pathname))return;
 const path=u.pathname.slice(BASE.pathname.length);
 // JSON has no per-file fallback/cache. app.js commits verified complete snapshots.
 if(path.endsWith('.json')){event.respondWith(fetch(r));return}
 const asset=path===''?'index.html':path;
 if(!Object.hasOwn(RELEASE.files,asset))return;
 event.respondWith((async()=>{
  const cache=await caches.open(CACHE),key=new URL(asset,BASE).href,hit=await cache.match(key);
  if(hit)return hit;
  const response=await fetch(new URL(asset,BASE),{cache:'no-store'});
  if(!response.ok)return response; // 404/500 are never cached.
  if(await hash(await response.clone().arrayBuffer())!==RELEASE.files[asset])return new Response('アプリの世代が一致しません。画面を閉じて開き直してください。',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}});
  await cache.put(key,response.clone());return response;
 })());
});
